# Jenkins uses this pod to read the backup volume.
apiVersion: v1
kind: Pod
metadata:
  name: POD_NAME
spec:
  securityContext:
    # Specify fsGroup so that the persistent volume is writable for the
    # non-privileged uid/gid 1001, which is used in the Dockerfile.
    fsGroup: 1001
  volumes:
    - name: database-backup
      gcePersistentDisk:
        fsType: ext4
        pdName: SOURCE_NAMESPACE-database-backup-disk
  containers:
    - name: backups
      image: centos/postgresql-12-centos7
      resources:
        limits:
          cpu: 100m
          memory: 10Mi
        requests:
          cpu: 100m
          memory: 10Mi
      command:
        - sleep
        - infinity
      env:
        - name: TZ
          value: Europe/Zurich
      volumeMounts:
        - name: database-backup
          mountPath: /database-backup
          readOnly: true
  restartPolicy: Never
  