source "https://rubygems.org"

# gem "google-cloud"
gem "google-cloud-tasks", "~>2.4"
gem "k8s-ruby"
gem "puma"
gem "sinatra"

group :test do
  gem "rack-test"
  gem "rspec"
  gem "rspec_junit_formatter"
end

group :development do
  gem "google-style"
  gem "pry"
  gem "rubocop"
  gem "ruby-lsp"
end
