source "https://rubygems.org"

# gem "google-cloud"
gem "google-cloud-tasks", "~>2.4"
gem "k8s-ruby"
gem "puma"
gem "sinatra"

group :test do
  gem "rack-test"
  gem "rspec"
  gem "rspec_junit_formatter"
end

group :development do
  gem "binding_of_caller"
  gem "pry"
  gem "pry-byebug"
  gem "reek"
  gem "rubocop"
  gem "ruby-lsp"
  gem "standard", ">= 1.35.1"
end
